from __future__ import annotations

"""The tool test matrix: one or more scenarios per Allegro-agent tool.

Each case is a real tool call with real arguments. `question` is the Polish
question a seller would ask to trigger it — it is what the screenshot run types
into the chat, so the captured conversation reads like an actual session.
"""

from dataclasses import dataclass, field
from datetime import date
from typing import Any

from tests.tools import dataset as ds

_TODAY = date.today()
_MONTH_START = _TODAY.replace(day=1).isoformat()
_TODAY_ISO = _TODAY.isoformat()


@dataclass(frozen=True)
class Case:
    id: str
    tool: str
    args: dict[str, Any]
    question: str
    expect: tuple[str, ...] = ()
    monitors: dict[str, bool] = field(default_factory=dict)
    empty: bool = False
    # Cases that are rejected by local validation and must never reach the API.
    no_api: bool = False
    note: str = ""


CASES: list[Case] = [
    # ── Zamówienia ───────────────────────────────────────────────────────────
    Case("get_new_orders", "get_new_orders", {},
         "Jakie mam nowe zamówienia?",
         ("**Zamówienie**", "Wysyłka do", "po terminie", "Włącz automatyczne sprawdzanie"),
         note="Trzy nowe zamówienia + blok statusu monitoringu (wyłączony)."),
    Case("get_new_orders__count", "get_new_orders", {"count_only": True},
         "Ile mam nowych zamówień?",
         ("Liczba nowych zamówień: 3",), monitors={"order": True},
         note="count_only — sama liczba; monitoring włączony, więc przycisk wyłączania."),
    Case("get_new_orders__last", "get_new_orders", {"limit": 1},
         "Pokaż ostatnie nowe zamówienie",
         ("**Zamówienie**",),
         note="limit=1 — liczba pojedyncza ('ostatnie zamówienie')."),
    Case("get_new_orders__empty", "get_new_orders", {},
         "Jakie mam nowe zamówienia?",
         ("Brak nowych zamówień.",), empty=True,
         note="Pusty sklep — stan zerowy."),
    Case("get_orders", "get_orders", {"limit": 10},
         "Pokaż listę wszystkich zamówień",
         ("**Zamówienie**", "Status realizacji", "Link:"),
         note="Pełna lista z linkami do panelu Allegro."),
    Case("get_orders__period", "get_orders",
         {"bought_after_local": f"{_MONTH_START} 00:00", "limit": 50},
         "Pokaż zamówienia z tego miesiąca",
         ("**Zamówienie**",),
         note="Filtr czasu zakupu (bought_after_local) → boughtAt.gte w API."),
    Case("get_order_details", "get_order_details", {"order_id": ds.ORD_1},
         f"Szczegóły zamówienia {ds.ORD_1}",
         ("Order ID:", "Items:", "BILLING", "ZYSK NETTO"),
         note="Zamówienie + wpisy rozliczeniowe + status faktury w jednym."),
    Case("get_orders_delivery", "get_orders_delivery", {},
         "Które zamówienia czekają na wysyłkę?",
         ("Podsumowanie kurierów", "Numer śledzenia", "Punkt odbioru"),
         note="Gotowe do wysyłki + mapowanie kurierów i linki do śledzenia."),
    Case("get_orders_delivery__sent", "get_orders_delivery", {"fulfillment_status": "SENT"},
         "Co już poszło do klientów?",
         ("Podsumowanie kurierów", "JJD000390007312345678"),
         note="Etap WYSŁANE — ten sam widok kurierski, ale dla paczek już nadanych."),

    # ── Oferty i stany magazynowe ────────────────────────────────────────────
    Case("get_active_offers", "get_active_offers", {},
         "Pokaż moje aktywne oferty",
         ("unikalnych produktów", "stan:"),
         note="Agregacja po nazwie + oferty zakończone przez wyprzedanie."),
    Case("get_active_offers__name", "get_active_offers", {"name": "ekspres"},
         "Pokaż oferty z ekspresami",
         ("Ekspres do kawy",),
         note="Filtr po nazwie — zapytanie do API z parametrem name."),
    Case("get_offers_summary", "get_offers_summary", {},
         "Podsumuj moje oferty",
         ("Podsumowanie ofert", "Stany magazynowe", "Ceny"),
         note="Statystyka zbiorcza — koszyki stanów i cen."),
    Case("query_offers_by_stock", "query_offers_by_stock", {"max_stock": 5},
         "Które produkty mają mniej niż 5 sztuk?",
         ("Znaleziono", "stan łącznie"),
         note="Filtr stanu magazynowego (≤ 5 szt.)."),
    Case("query_offers_by_price", "query_offers_by_price", {"min_price": 100, "max_price": 600},
         "Pokaż oferty w cenie od 100 do 600 zł",
         ("Znaleziono", "stan:"),
         note="Filtr cenowy — oferty posortowane rosnąco."),
    Case("get_products_to_reorder", "get_products_to_reorder", {"max_stock": 5},
         "Co muszę domówić do magazynu?",
         ("Produkty do zamówienia", "zakończona — wyprzedana"),
         note="Braki magazynowe razem z produktami wyprzedanymi do zera."),
    Case("get_offer_details", "get_offer_details", {"offer_id": "14587236901"},
         "Pokaż szczegóły oferty 14587236901",
         ('"id"', '"sellingMode"'),
         note="Surowy JSON oferty z Allegro (obcięty do 3000 znaków)."),
    Case("update_offer_price", "update_offer_price",
         {"offer_id": "14587236901", "price": 379.99},
         "Zmień cenę oferty 14587236901 na 379,99 zł",
         ("Price updated successfully",),
         note="Zapis do API — realna zmiana ceny oferty."),
    Case("update_offer_price__invalid", "update_offer_price",
         {"offer_id": "14587236901", "price": 0},
         "Ustaw cenę oferty 14587236901 na 0 zł",
         ("Error: price must be greater than 0.",), no_api=True,
         note="Walidacja — cena 0 odrzucona przed wysłaniem do Allegro."),
    Case("update_offer_stock", "update_offer_stock",
         {"offer_id": "14587355001", "available": 25},
         "Ustaw stan oferty 14587355001 na 25 sztuk",
         ("Stock updated to 25",),
         note="Zapis do API — aktualizacja stanu magazynowego."),

    # ── Wiadomości ───────────────────────────────────────────────────────────
    Case("get_message_threads", "get_message_threads", {},
         "Pokaż wiadomości od kupujących",
         ("Thread", "Unread:"),
         note="Lista wątków z informacją o nieprzeczytanych."),
    Case("get_message_threads__count", "get_message_threads", {"count_only": True},
         "Czy mam nowe wiadomości?",
         ("Unread count: 2",),
         note="count_only — odpowiedź typu tak/nie + liczba."),
    Case("get_thread_messages", "get_thread_messages", {"thread_id": ds.THREAD_1},
         "Przeczytaj treść wiadomości od anna.kowalska88",
         ("Kupujący", "Sprzedawca", "gwarancj"),
         note="Treść konkretnego wątku (kto, kiedy, co napisał)."),
    Case("get_thread_messages__by_buyer", "get_thread_messages",
         {"buyer_login": "marek_zielinski"},
         "Co napisał marek_zielinski?",
         ("Buyer: marek_zielinski", "odkurzacza"),
         note="Bez thread_id — wątek dopasowany po loginie kupującego."),
    Case("send_message_to_buyer", "send_message_to_buyer",
         {"thread_id": ds.THREAD_1,
          "text": "Dzień dobry, paczka zostanie nadana jeszcze dziś. Pozdrawiam!"},
         "Odpisz Annie, że paczka pójdzie dziś",
         ("Message sent successfully",),
         note="Zapis do API — realna wysyłka wiadomości do kupującego."),

    # ── Konto i rozliczenia ──────────────────────────────────────────────────
    Case("get_account_info", "get_account_info", {},
         "Pokaż dane mojego konta",
         ("Login:", "Company:"),
         note="Dane konta sprzedawcy z /me."),
    Case("get_billing_summary", "get_billing_summary", {"limit": 50},
         "Jakie opłaty naliczyło mi Allegro?",
         ("Koszty Allegro", "Podział wg rodzaju", "transfer wewnętrzny"),
         note="Wpisy rozliczeniowe; PAD pokazany, ale wyłączony z sum."),
    Case("get_billing_summary__period", "get_billing_summary",
         {"date_from_local": _MONTH_START, "date_to_local": _TODAY_ISO},
         f"Pokaż koszty Allegro od {_MONTH_START} do {_TODAY_ISO}",
         ("Koszty Allegro", _MONTH_START),
         note="Ten sam raport zawężony do zakresu dat."),
    Case("get_sales_summary", "get_sales_summary",
         {"date_from_local": _MONTH_START, "date_to_local": _TODAY_ISO},
         "Ile zarobiłem w tym miesiącu?",
         ("Podsumowanie sprzedaży", "Top produkty", "Przychód po opłatach Allegro"),
         note="Przychód, opłaty i zestawienie per zamówienie (format dashboard)."),

    # ── Faktury ──────────────────────────────────────────────────────────────
    Case("get_orders_pending_invoice", "get_orders_pending_invoice", {},
         "Do których zamówień muszę wystawić fakturę?",
         ("Zamówień bez faktury", "Faktura: niewystawiona", "NIP"),
         note="Zamówienia z prośbą o fakturę + dane nabywcy."),
    Case("get_order_invoice_data", "get_order_invoice_data", {"order_id": ds.ORD_1},
         f"Jakie są dane do faktury dla zamówienia {ds.ORD_1}?",
         ("Dane do faktury", "NIP", "Kod pocztowy"),
         note="Adres i NIP do faktury dla jednego zamówienia."),
    Case("get_order_invoice_data__none", "get_order_invoice_data", {"order_id": ds.ORD_3},
         f"Dane do faktury dla zamówienia {ds.ORD_3}",
         ("zrezygnował z faktury",),
         note="Kupujący zaznaczył 'nie chcę faktury'."),
    Case("preview_pending_invoices", "preview_pending_invoices", {},
         "Pokaż podgląd faktur do wystawienia",
         ("Podgląd danych faktur", "```json", "services"),
         note="Payload inFakt bez wysyłki — nic nie trafia do inFakt."),
    Case("issue_invoice_for_order", "issue_invoice_for_order", {"order_id": ds.ORD_1},
         f"Wystaw fakturę dla zamówienia {ds.ORD_1}",
         ("✅ Faktura", "infakt.pl/share", "firma"),
         note="Realne wystawienie jednej faktury w inFakt + link do podglądu."),
    Case("issue_invoice_for_order__exists", "issue_invoice_for_order", {"order_id": ds.ORD_6},
         f"Wystaw fakturę dla zamówienia {ds.ORD_6}",
         ("faktura już istnieje",),
         note="Zabezpieczenie przed podwójną fakturą."),
    Case("issue_invoice_for_order__not_requested", "issue_invoice_for_order",
         {"order_id": ds.ORD_3},
         f"Wystaw fakturę dla zamówienia {ds.ORD_3}",
         ("nie poprosił o fakturę",),
         note="Kupujący nie chciał faktury — nic nie zostaje wystawione."),
    Case("attach_invoice_to_allegro_order", "attach_invoice_to_allegro_order",
         {"order_id": ds.ORD_1, "invoice_uuid": ds.INFAKT_INVOICE_UUID},
         "Dołącz tę fakturę do zamówienia w Allegro",
         ("✅ Faktura", "dołączona do zamówienia"),
         note="Pobranie PDF z inFakt i upload do Allegro (2 kroki API)."),
    Case("attach_invoice_to_allegro_order__404", "attach_invoice_to_allegro_order",
         {"order_id": ds.ORD_1, "invoice_uuid": "00000000-0000-0000-0000-000000000000"},
         "Dołącz fakturę 00000000-0000-0000-0000-000000000000 do zamówienia",
         ("❌", "404"),
         note="Nieznane ID faktury — czytelny komunikat błędu zamiast wyjątku."),
    Case("send_invoice_to_ksef", "send_invoice_to_ksef",
         {"invoice_uuid": ds.INFAKT_INVOICE_UUID},
         "Wyślij tę fakturę do KSeF",
         ("📤", "KSeF", "sent"),
         note="Zgłoszenie faktury do KSeF (asynchroniczne po stronie inFakt)."),

    # ── Zwroty i reklamacje ──────────────────────────────────────────────────
    Case("get_new_returns", "get_new_returns", {},
         "Czy mam nowe zwroty?",
         ("**Zwrot**", "Status:"),
         note="Wszystkie zwroty + blok monitoringu zwrotów."),
    Case("get_new_returns__count", "get_new_returns", {"count_only": True},
         "Ile mam zwrotów?",
         ("Liczba zwrotów: 4",),
         note="count_only — sama liczba zwrotów."),
    Case("get_returns_to_process", "get_returns_to_process", {},
         "Które zwroty muszę obsłużyć?",
         ("**Zwrot**", "DELIVERED"),
         note="Tylko zwroty, których paczka już wróciła (status DELIVERED)."),
    Case("get_new_complaints", "get_new_complaints", {},
         "Czy mam nowe reklamacje?",
         ("Reklamacja/spór", "Termin decyzji"),
         note="Spory i reklamacje z /sale/issues wraz z terminem decyzji."),

    # ── Monitoring (przyciski w UI) ──────────────────────────────────────────
    Case("suggest_order_monitoring", "suggest_order_monitoring", {},
         "Czy możesz mnie informować o nowych zamówieniach?",
         ("Włącz automatyczne sprawdzanie",),
         note="Monitoring wyłączony → przycisk włączenia."),
    Case("disable_order_monitoring", "disable_order_monitoring", {},
         "Wyłącz powiadomienia o zamówieniach",
         ("Wyłącz automatyczne sprawdzanie",), monitors={"order": True},
         note="Monitoring włączony → status + przycisk wyłączenia."),
    Case("suggest_invoice_monitoring", "suggest_invoice_monitoring", {},
         "Powiadamiaj mnie o zamówieniach z fakturą",
         ("Włącz monitoring faktur",),
         note="Monitoring faktur wyłączony → przycisk włączenia."),
    Case("disable_invoice_monitoring", "disable_invoice_monitoring", {},
         "Wyłącz monitoring faktur",
         ("Wyłącz monitoring faktur",), monitors={"invoice": True},
         note="Monitoring faktur włączony → przycisk wyłączenia."),
    Case("suggest_invoice_reminder", "suggest_invoice_reminder", {},
         "Przypominaj mi o niewystawionych fakturach",
         ("Włącz przypomnienia o fakturach",),
         note="Przypomnienia (co 2 h, 7:00–20:00) wyłączone → przycisk włączenia."),
    Case("disable_invoice_reminder", "disable_invoice_reminder", {},
         "Nie przypominaj mi o fakturach",
         ("Wyłącz przypomnienia o fakturach",), monitors={"invoice_reminder": True},
         note="Przypomnienia włączone → status + przycisk wyłączenia."),
    Case("suggest_message_monitoring", "suggest_message_monitoring", {},
         "Daj znać, gdy kupujący napisze",
         ("Włącz monitoring wiadomości",),
         note="Monitoring wiadomości wyłączony → przycisk włączenia."),
    Case("disable_message_monitoring", "disable_message_monitoring", {},
         "Wyłącz monitoring wiadomości",
         ("Wyłącz monitoring wiadomości",), monitors={"message": True},
         note="Monitoring wiadomości włączony → przycisk wyłączenia."),
    Case("suggest_returns_monitoring", "suggest_returns_monitoring", {},
         "Informuj mnie o nowych zwrotach i reklamacjach",
         ("Włącz monitoring zwrotów",),
         note="Monitoring zwrotów wyłączony → przycisk włączenia."),
    Case("disable_returns_monitoring", "disable_returns_monitoring", {},
         "Wyłącz monitoring zwrotów",
         ("Wyłącz monitoring zwrotów",), monitors={"returns": True},
         note="Monitoring zwrotów włączony → przycisk wyłączenia."),
]

CASES_BY_ID = {c.id: c for c in CASES}
COVERED_TOOLS = {c.tool for c in CASES}
